import { useEffect, useRef, useState, type ReactNode } from 'react'
import { X } from 'lucide-react'
type Edge = 'n'|'s'|'e'|'w'|'ne'|'nw'|'se'|'sw'
type Rect = { left:number; top:number; width:number; height:number }
const EDGES: Edge[] = ['n','s','e','w','ne','nw','se','sw']
export function FloatingPreview({ open, title, onClose, children, footer }: { open:boolean; title:string; onClose:()=>void; children:ReactNode; footer?:ReactNode }) {
  const [rect,setRect]=useState<Rect>({left:120,top:80,width:720,height:560})
  const action=useRef<{mode:'drag'|'resize';edge?:Edge;x:number;y:number;rect:Rect}|null>(null)
  useEffect(()=>{ if(!open)return; const move=(e:PointerEvent)=>{const a=action.current;if(!a)return;const dx=e.clientX-a.x,dy=e.clientY-a.y;if(a.mode==='drag'){setRect({...a.rect,left:Math.max(8,a.rect.left+dx),top:Math.max(8,a.rect.top+dy)});return}let {left,top,width,height}=a.rect;const minW=320,minH=220;if(a.edge?.includes('e'))width=Math.max(minW,a.rect.width+dx);if(a.edge?.includes('s'))height=Math.max(minH,a.rect.height+dy);if(a.edge?.includes('w')){width=Math.max(minW,a.rect.width-dx);left=a.rect.left+a.rect.width-width}if(a.edge?.includes('n')){height=Math.max(minH,a.rect.height-dy);top=a.rect.top+a.rect.height-height}setRect({left:Math.max(8,left),top:Math.max(8,top),width,height})};const end=()=>{action.current=null;document.body.style.userSelect=''};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end);window.addEventListener('blur',end);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',end);window.removeEventListener('blur',end);end()}},[open])
  if(!open)return null
  const drag=(e:React.PointerEvent)=>{if((e.target as HTMLElement).closest('button'))return;e.preventDefault();action.current={mode:'drag',x:e.clientX,y:e.clientY,rect};document.body.style.userSelect='none'}
  const resize=(edge:Edge,e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.stopPropagation();action.current={mode:'resize',edge,x:e.clientX,y:e.clientY,rect};document.body.style.userSelect='none'}
  return <div className='fixed inset-0 z-[1200] bg-black/45 backdrop-blur-[2px]' onPointerDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role='dialog' aria-label={title} className='absolute flex min-h-0 min-w-0 max-w-[calc(100vw-16px)] max-h-[calc(100vh-16px)] flex-col overflow-visible rounded-xl bg-[var(--color-bg-primary)] shadow-[0_24px_80px_rgba(0,0,0,.42)] outline-none' style={rect}><header onPointerDown={drag} className='relative z-10 flex h-12 shrink-0 cursor-move items-center justify-between rounded-t-xl border-b border-[color-mix(in_srgb,var(--color-border)_55%,transparent)] bg-[var(--color-bg-secondary)] px-5 font-semibold'><span className='truncate'>{title}</span><button type='button' onPointerDown={e=>e.stopPropagation()} onClick={onClose} className='grid size-8 place-items-center rounded-lg outline-none hover:bg-black/10'><X size={18}/></button></header><div className='relative z-0 min-h-0 min-w-0 flex-1 overflow-auto p-5'>{children}</div>{footer?<footer className='relative z-10 shrink-0 rounded-b-xl border-t border-[color-mix(in_srgb,var(--color-border)_55%,transparent)] bg-[var(--color-bg-secondary)] px-5 py-3'>{footer}</footer>:null}{EDGES.map(edge=><button key={edge} type='button' aria-label={`调整预览窗口${edge}大小`} onPointerDown={e=>resize(edge,e)} className={`group absolute z-20 block touch-none border-0 bg-transparent p-0 opacity-0 hover:opacity-100 focus-visible:opacity-100 ${edge==='n'?'left-3 right-3 top-[-8px] h-4 cursor-n-resize':edge==='s'?'bottom-[-8px] left-3 right-3 h-4 cursor-s-resize':edge==='e'?'bottom-3 right-[-8px] top-3 w-4 cursor-e-resize':edge==='w'?'bottom-3 left-[-8px] top-3 w-4 cursor-w-resize':edge==='ne'?'right-[-8px] top-[-8px] size-5 cursor-ne-resize':edge==='nw'?'left-[-8px] top-[-8px] size-5 cursor-nw-resize':edge==='se'?'bottom-[-8px] right-[-8px] size-5 cursor-se-resize':'bottom-[-8px] left-[-8px] size-5 cursor-sw-resize'}`}><span className='pointer-events-none absolute inset-1 rounded-md border border-[var(--color-accent)]/45 bg-[var(--color-accent)]/10'/></button>)}</section></div>
}
